/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "typedef.h"

#define set(Register,Pin_num) 		(Register|= 1<<Pin_num)
#define reset(Register,Pin_num) 	(Register&= ~(1<<Pin_num))


#define RCC_BASE 0x40021000
#define RCC_APB2EN_OFFSET 0x18
#define RCC_APB2EN *((volatile uint32_t *)(RCC_BASE + RCC_APB2EN_OFFSET))

#define GPIOA_BASE 0x40010800
#define GPIOA_CRL *(volatile uint32_t * )(GPIOA_BASE+0x00)
#define GPIOA_ODR *(volatile uint32_t * )(GPIOA_BASE+0x0C)


int main(void)
{
	set(RCC_APB2EN,2);
	set(GPIOA_CRL,0);
	set(GPIOA_CRL,1);
	reset(GPIOA_CRL,2);
	reset(GPIOA_CRL,3);

	while(1){
		set(GPIOA_ODR,0);
		for(uint32_t i=0; i<500000;i++);
		reset(GPIOA_ODR,0);
		for(uint32_t i=0; i<500000;i++);

	}

}
